language: node_js
node_js:
  - "5.10"
  - "4.4"
services:
  - docker
before_install:
  - docker pull localstack/localstack
  - docker run -d -p 4567-4582:4567-4582 -p 8080:8080 localstack/localstack
script:
  - npm run test
  - npm run integ
